#include <Ethernet.h>
void website(EthernetClient &client, uint8_t IPaddr[], uint8_t inputNumber[], const char* status, const char* save, uint8_t brightness[], const char* version){
     client.print("<!DOCTYPE html>");
     client.print("<html>");
     client.print("");
     client.print("<head>");
     client.print("<title>TLS configuration</title>");
     client.print("<link rel=\"icon\" href=\"data:,\">");
     client.print("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
     client.print("<style>");
     client.print("body {");
     client.print("font-family: 'Arial', 'Helvetica', 'Verdana', sans-serif;");
     client.print("}");
     client.print("#loader {");
     client.print("position: absolute;");
     client.print("right: 35%;");
     client.print("border: 5px solid #ffffff;");
     client.print("border-radius: 50%;");
     client.print("border-top: 5px solid #666;");
     client.print("width: 25px;");
     client.print("height: 25px;");
     client.print("-webkit-animation: spin 1s linear infinite;");
     client.print("animation: spin 1s linear infinite;");
     client.print("}");
     client.print("");
     client.print("@-webkit-keyframes spin {");
     client.print("0% {");
     client.print("-webkit-transform: rotate(0deg);");
     client.print("}");
     client.print("");
     client.print("100% {");
     client.print("-webkit-transform: rotate(360deg);");
     client.print("}");
     client.print("}");
     client.print("");
     client.print("@keyframes spin {");
     client.print("0% {");
     client.print("transform: rotate(0deg);");
     client.print("}");
     client.print("");
     client.print("100% {");
     client.print("transform: rotate(360deg);");
     client.print("}");
     client.print("}");
     client.print("");
     client.print("input[type=text],");
     client.print("input[type=number],");
     client.print("select,");
     client.print("textarea {");
     client.print("width: 50%;");
     client.print("padding: 12px;");
     client.print("border: 1px solid #ccc;");
     client.print("border-radius: 4px;");
     client.print("box-sizing: border-box;");
     client.print("margin-top: 6px;");
     client.print("margin-bottom: 16px;");
     client.print("resize: vertical;");
     client.print("}");
     client.print("");
     client.print("label {");
     client.print("display: block;");
     client.print("}");
     client.print("");
     client.print("input[type=text]#IPaddr {");
     client.print("            width: calc(100% - 200px);");
     client.print("        }");
     client.print("");
     client.print("        .input-group {");
     client.print("width: 50%;");
     client.print("margin: 0 auto;");
     client.print("            display: flex;");
     client.print("            align-items: center;");
     client.print("            margin-bottom: 16px;");
     client.print("        }");
     client.print("");
     client.print("        .input-group label {");
     client.print("            margin-right: 30px;");
     client.print("            width: 200px;");
     client.print("            text-align: right;");
     client.print("padding-bottom: 8px;");
     client.print("        }");
     client.print("");
     client.print("input[type=submit],");
     client.print("button {");
     client.print("background-color: #4CAF50;");
     client.print("color: white;");
     client.print("padding: 12px 20px;");
     client.print("border: none;");
     client.print("border-radius: 4px;");
     client.print("cursor: pointer;");
     client.print("}");
     client.print("");
     client.print("button {");
     client.print("background-color: red;");
     client.print("margin-left: 3px;");
     client.print("}");
     client.print("");
     client.print("button:hover {");
     client.print("background-color: rgb(207, 0, 0);");
     client.print("}");
     client.print("");
     client.print(".button {");
     client.print("background-color: #4CAF50;");
     client.print("color: white;");
     client.print("padding: 12px 20px;");
     client.print("border: none;");
     client.print("border-radius: 4px;");
     client.print("cursor: pointer;");
     client.print("width: 100px;");
     client.print("margin: 0 4px;");
     client.print("}");
     client.print("");
     client.print("input[type=submit].button {");
     client.print("width: 120px;");
     client.print("font-family: Arial, Helvetica, sans-serif;");
     client.print("font-size: 14px;");
     client.print("}");
     client.print("");
     client.print("a.button.refresh {");
     client.print("background-color: #666;");
     client.print("text-decoration: none;");
     client.print("font-family: Arial, Helvetica, sans-serif;");
     client.print("font-size: 14px;");
     client.print("}");
     client.print("");
     client.print(".button:hover {");
     client.print("background-color: #45a049;");
     client.print("}");
     client.print("");
     client.print("a.button.refresh:hover {");
     client.print("background-color: rgb(134, 134, 134);");
     client.print("}");
     client.print("");
     client.print(".buttons {");
     client.print("clear: both;");
     client.print("padding: 20px 0 0 0;");
     client.print("text-align: center;");
     client.print("}");
     client.print("");
     client.print(".buttons>* {");
     client.print("display: inline-block;");
     client.print("}");
     client.print("");
     client.print(".container {");
     client.print("position: relative;");
     client.print("border-radius: 5px;");
     client.print("background-color: #f2f2f2;");
     client.print("padding: 20px;");
     client.print("margin-left: auto;");
     client.print("margin-right: auto;");
     client.print("width: 50%;");
     client.print("}");
     client.print("");
     client.print("#connected {");
     client.print("color: #4CAF50;");
     client.print("margin-top: 10px;");
     client.print("text-align: center;");
     client.print("}");
     client.print("");
     client.print("#disconnected {");
     client.print("color: red;");
     client.print("margin-top: 10px;");
     client.print("text-align: center;");
     client.print("}");
     client.print("");
     client.print("#footer {");
     client.print("position: fixed;");
     client.print("bottom: 10px;");
     client.print("right: 10px;");
     client.print("}");
     client.print("");
     client.print("table {");
     client.print("width: 80%;");
     client.print("border-collapse: collapse;");
     client.print("margin: 0 auto;");
     client.print("margin-bottom: 20px;");
     client.print("}");
     client.print("");
     client.print("th,");
     client.print("td {");
     client.print("padding: 2px;");
     client.print("text-align: center;");
     client.print("}");
     client.print("");
     client.print("td label{");
     client.print("padding-bottom: 8px;");
     client.print("}");
     client.print("");
     client.print("th {");
     client.print("background-color: #f2f2f2;");
     client.print("}");
     client.print("");
     client.print(".slider {");
     client.print("appearance: none;");
     client.print("width: 80%;");
     client.print("height: 10px;");
     client.print("background: #ddd;");
     client.print("border-radius: 5px;");
     client.print("outline: none;");
     client.print("opacity: 0.7;");
     client.print("transition: opacity .2s;");
     client.print("}");
     client.print("");
     client.print(".slider:hover {");
     client.print("opacity: 1;");
     client.print("}");
     client.print("");
     client.print(".slider::-webkit-slider-thumb {");
     client.print("-webkit-appearance: none;");
     client.print("appearance: none;");
     client.print("width: 20px;");
     client.print("height: 20px;");
     client.print("background: #4CAF50;");
     client.print("cursor: pointer;");
     client.print("border-radius: 50%;");
     client.print("}");
     client.print("");
     client.print(".slider::-moz-range-thumb {");
     client.print("width: 25px;");
     client.print("height: 25px;");
     client.print("background: #4CAF50;");
     client.print("cursor: pointer;");
     client.print("border-radius: 50%;");
     client.print("}");
     client.print("</style>");
     client.print("</head>");
     client.print("");
     client.print("<body>");
     client.print("<script>");
     client.print("document.addEventListener(\"DOMContentLoaded\", function () {");
     client.print("var loader = document.getElementById('loader');");
     client.print("if (window.location.href.indexOf('IPaddr') > -1) {");
     client.print("loader.style.display = 'block';");
     client.print("setTimeout(function () {");
     client.print("window.location.replace(\"/\");");
     client.print("}, 1000);");
     client.print("} else {");
     client.print("loader.style.display = 'none';");
     client.print("}");
     client.print("});");
     client.print("</script>");
     client.print("");
     client.print("<h3 style=\"text-align: center;\">Tally Light System configuration <br> for vMix switchers</h3>");
     client.print("");
     client.print("<div class=\"container\">");
     client.print("<form id=\"form\" action=\"\">");
     client.print("<div class=\"input-group\">");
     client.print("<label for=\"IPaddr\">vMix switcher IP address</label>");
     client.print("<input type=\"text\" id=\"IPaddr\" name=\"IPaddr\" placeholder=\"IP address\"");
     client.print("value=\"");
     client.print(IPaddr[0]);
     client.print(".");
     client.print(IPaddr[1]);
     client.print(".");
     client.print(IPaddr[2]);
     client.print(".");
     client.print(IPaddr[3]);
     client.print("\">");
     client.print("</div>");
     client.print("<div id=\"loader\"></div>");
     client.print("");
     client.print(status);
     client.print("");
     client.print("<table>");
     client.print("<thead>");
     client.print("<tr id=\"rnumber\">");
     client.print("<th>Receiver number</th>");
     client.print("<th>vMix input number</th>");
     client.print("<th>Brightness</th>");
     client.print("</tr>");
     client.print("</thead>");
     client.print("<tbody>");
     client.print("<tr>");
     client.print("<td><label for=\"T1\">1.</label></td>");
     client.print("<td><input type=\"number\" min=\"0\" max=\"255\" id=\"T1\" name=\"T1\" placeholder=\"vMix input number\"");
     client.print("value=\"");
     client.print(inputNumber[0]);
     client.print("\"></td>");
     client.print("<td><input type=\"range\" min=\"1\" max=\"6\" step=\"1\" id=\"B1\" class=\"slider\" name=\"B1\"");
     client.print("value=\"");
     client.print(brightness[0]);
     client.print("\"></td>");
     client.print("</tr>");
     client.print("<tr>");
     client.print("<td><label for=\"T2\">2.</label></td>");
     client.print("<td><input type=\"number\" min=\"0\" max=\"255\" id=\"T2\" name=\"T2\" placeholder=\"vMix input number\"");
     client.print("value=\"");
     client.print(inputNumber[1]);
     client.print("\"></td>");
     client.print("<td><input type=\"range\" min=\"1\" max=\"6\" step=\"1\" id=\"B2\" class=\"slider\" name=\"B2\"");
     client.print("value=\"");
     client.print(brightness[1]);
     client.print("\"></td>");
     client.print("</tr>");
     client.print("<tr>");
     client.print("<td><label for=\"T3\">3.</label></td>");
     client.print("<td><input type=\"number\" min=\"0\" max=\"255\" id=\"T3\" name=\"T3\" placeholder=\"vMix input number\"");
     client.print("value=\"");
     client.print(inputNumber[2]);
     client.print("\"></td>");
     client.print("<td><input type=\"range\" min=\"1\" max=\"6\" step=\"1\" id=\"B3\" class=\"slider\" name=\"B3\"");
     client.print("value=\"");
     client.print(brightness[2]);
     client.print("\"></td>");
     client.print("</tr>");
     client.print("<tr>");
     client.print("<td><label for=\"T4\">4.</label></td>");
     client.print("<td><input type=\"number\" min=\"0\" max=\"255\" id=\"T4\" name=\"T4\" placeholder=\"vMix input number\"");
     client.print("value=\"");
     client.print(inputNumber[3]);
     client.print("\"></td>");
     client.print("<td><input type=\"range\" min=\"1\" max=\"6\" step=\"1\" id=\"B4\" class=\"slider\" name=\"B4\"");
     client.print("value=\"");
     client.print(brightness[3]);
     client.print("\"></td>");
     client.print("</tr>");
     client.print("<tr>");
     client.print("<td><label for=\"T5\">5.</label></td>");
     client.print("<td><input type=\"number\" min=\"0\" max=\"255\" id=\"T5\" name=\"T5\" placeholder=\"vMix input number\"");
     client.print("value=\"");
     client.print(inputNumber[4]);
     client.print("\"></td>");
     client.print("<td><input type=\"range\" min=\"1\" max=\"6\" step=\"1\" id=\"B5\" class=\"slider\" name=\"B5\"");
     client.print("value=\"");
     client.print(brightness[4]);
     client.print("\"></td>");
     client.print("</tr>");
     client.print("</tbody>");
     client.print("</table>");
     client.print("");
     client.print("<div class=\"buttons\">");
     client.print("<a class=\"button refresh\" href=\"/\">Refresh</a>");
     client.print("<input class=\"button\" type=\"Submit\" value=\"Submit\">");
     client.print("");
     client.print(save);
     client.print("");
     client.print("</div>");
     client.print("</form>");
     client.print("<div id=\"footer\">");
     client.print(version);
     client.print(" &copy eMT</div>");
     client.print("</div>");
     client.print("</body>");
     client.print("");
     client.print("</html>");
}